name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - master # This assumes your main branch is 'master'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18 # Use Node.js 18 or later

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Docusaurus website
        run: yarn build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # The directory where Docusaurus builds your site
          # The branch Docusaurus typically expects for deployment is 'gh-pages'
          publish_branch: gh-pages
